version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ${APP_PATH_HOST}:/var/www
        ports:
            - "8080:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ${APP_PATH_HOST}:/var/www
        links:
            - mysql
            - redis
            - mongo
            - postgres
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
#    php-cli:
#        build:
#            context: ./
#            dockerfile: docker/php-cli.docker
#        volumes:
#            - ${APP_PATH_HOST}:/var/www
#        links:
#            - mysql
#            - redis
#        environment:
#            - "DB_PORT=3306"
#            - "DB_HOST=mysql"
#            - "REDIS_PORT=6379"
#            - "REDIS_HOST=redis"
#        tty: true
    mysql:
        image: mysql:5.7
        volumes:
            - ${DB_PATH_HOST}/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=mysqldb"
        ports:
            - "33061:3306"
    redis:
        image: redis:5.0
        ports:
            - "63791:6379"
    node:
        image: node:8.6-alpine
        volumes:
            - ${APP_PATH_HOST}:/var/www
        working_dir: /var/www
        tty: true
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ${DB_PATH_HOST}/mongo:/data/db
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - ${DB_PATH_HOST}/postgres:/data/postgres
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: postgres
            PGDATA: /data/postgres